### ISSUE TITLE
Failed to download the-pile validate set

### ISSUE THREAD

**Issue by KnowingNothing** [kernelmachine/silo-lm#4]
I tried to use `download_data.py` to download the-pile:
`python download_data.py --subset the-pile`
The train set was downloaded but the validation set was not. The error message is
```
--2023-11-06 19:29:22--  https://the-eye.eu/public/AI/pile/val.jsonl.zst
Resolving the-eye.eu (the-eye.eu)... 162.213.130.6
Connecting to the-eye.eu (the-eye.eu)|162.213.130.6|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-06 19:29:23 ERROR 404: Not Found.

Failed to download the data
```
Is this because of a wrong url or something else?

**Comment by shmsw25** [comment]
Hi @KnowingNothing, thank you for your interest in our work. This is because the script downloads the Pile val/test data from the original host, and it turns out the original host recently stopped hosting the data. For now, I recommend you to download the data from our Google Drive:
* val.jsonl.zst: [https://drive.google.com/file/d/1oUFe3ul-Oah50pMgF8fW6hAT4qrp04cj](https://drive.google.com/file/d/1oUFe3ul-Oah50pMgF8fW6hAT4qrp04cj)
* test.jsonl.zst: [https://drive.google.com/file/d/1HuXhNG_3rivExolnKCTuzzMzX67ul3ys](https://drive.google.com/file/d/1HuXhNG_3rivExolnKCTuzzMzX67ul3ys)

We will explore more viable solutions in the future.

**Comment by KnowingNothing** [comment]
Thanks for your prompt reply!
